### ISSUE TITLE
Query error with Relay API

### ISSUE THREAD

**Issue by huy-nguyen** [prisma-labs/nextjs-graphql-api-examples#1]
When I make this simple query

```graphql
query {
  viewer {
    allUsers(first: 1) {
      edges {
        node {
          id
        }
      }
    }
  }
}
```

in the GraphiQL interface at `https://nextjs-graphql-with-prisma-relay.vercel.app/api`, I get this error:

```json
{
  "errors": [
    {
      "message": "error: Error validating datasource `db`: The URL for datasource `db` must start with the protocol `postgresql://`.\n  -->  schema.prisma:6\n   | \n 5 |   provider = \"postgres\"\n 6 |   url      = env(\"DATABASE_URL\")\n   | \n\nValidation Error Count: 1",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "viewer",
        "allUsers",
        "edges"
      ]
    }
  ],
  "data": {
    "viewer": {
      "allUsers": {
        "edges": null
      }
    }
  }
}
```

This causes the [NextJS + Relay modern example](https://github.com/vercel/next.js/tree/canary/examples/with-relay-modern) to fail.

**Comment by Jolg42** [comment]
It seems that it works now
https://nextjs-graphql-with-prisma-relay.vercel.app/api?query=query%20%7B%0A%20%20viewer%20%7B%0A%20%20%20%20allUsers(first%3A%201)%20%7B%0A%20%20%20%20%20%20edges%20%7B%0A%20%20%20%20%20%20%20%20node%20%7B%0A%20%20%20%20%20%20%20%20%20%20id%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D

<img width="1479" alt="Screen Shot 2021-12-23 at 17 35 18" src="https://user-images.githubusercontent.com/1328733/147268505-c84f17f9-2f0e-4f53-96fc-a45257e8b7b4.png">
