### ISSUE TITLE
It seems api link can't be found (404)

### ISSUE THREAD

**Issue by willy20040711** [prisma-labs/nextjs-graphql-api-examples#3]
The URL : https://nextjs-graphql-with-prisma-simple.vercel.app/api
Seems it can not be found.

**Comment by janpio** [comment]
The API is currently available at https://nextjs-graphql-with-prisma-simple-foo.vercel.app/api
Trying to figure out with Vercel if we can get the old host name back.

**Comment by janpio** [comment]
Here is a PR we could merge alternatively if we can not recover the old hostname: https://github.com/vercel/next.js/pull/32759

**Comment by leerob** [comment]
Merged!

**Comment by janpio** [comment]
Fixed in README
